const Types = {
  //Post
  POST_GET_ALL: "POST_GET_ALL",
  POST_GET_SINGLE: "POST_GET_SINGLE",
  POST_CREATE: "POST_CREATE",
  POST_EDIT: "POST_EDIT",
  POST_DELETE: "POST_DELETE",

  //Page
  PAGE_GET_ALL: "PAGE_GET_ALL",
  PAGE_GET_SINGLE: "PAGE_GET_SINGLE",
  PAGE_CREATE: "PAGE_CREATE",
  PAGE_EDIT: "PAGE_EDIT",
  PAGE_DELETE: "PAGE_DELETE",

  //Login
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

  //Register
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  //User
  USER_GET_ALL: "USER_GET_ALL",
  USER_GET_SINGLE: "USER_GET_SINGLE",
  USER_CREATE: "USER_CREATE",
  USER_EDIT: "USER_EDIT",
  USER_DELETE: "USER_DELETE",

  //Role
  ROLE_GET_ALL: "ROLE_GET_ALL",
  ROLE_GET_SINGLE: "ROLE_GET_SINGLE",
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_EDIT: "ROLE_EDIT",
  ROLE_DELETE: "ROLE_DELETE",
};

export default Types;
