const Types = {
  //Post
  POST_GET_ALL: "POST_GET_ALL",
  POST_GET_SINGLE: "POST_GET_SINGLE",
  POST_CREATE: "POST_CREATE",
  POST_EDIT: "POST_EDIT",
  POST_DELETE: "POST_DELETE",
};
export default Types;
